# Generated by Django 3.2.8 on 2021-11-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('clothingType', models.CharField(max_length=30)),
                ('materialType', models.CharField(max_length=30)),
                ('brandName', models.CharField(max_length=30)),
                ('ownerRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('memory', models.CharField(max_length=300)),
            ],
        ),
    ]
